"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var parser_1 = require("./process/parse/parser");
exports.parse = parser_1.parse;
exports.Parser = parser_1.Parser;
var attribue_expression_1 = require("./process/parse/states/attribue.expression");
exports.AttributeExpression = attribue_expression_1.default;
var comment_expression_1 = require("./process/parse/states/comment.expression");
exports.CommentExpression = comment_expression_1.default;
var name_1 = require("./process/parse/states/name");
exports.Name = name_1.default;
var node_expression_1 = require("./process/parse/states/node.expression");
exports.NodeExpression = node_expression_1.default;
var prolog_1 = require("./process/parse/states/prolog");
exports.PrologExpression = prolog_1.default;
var text_expression_1 = require("./process/parse/states/text.expression");
exports.TextExpression = text_expression_1.default;
var value_1 = require("./process/parse/states/value");
exports.Value = value_1.default;
//# sourceMappingURL=parser.js.map